// Generated by CoffeeScript 1.9.3
var SqlDom;

SqlDom = (function() {
  function SqlDom(query) {
    console.log(query);
    return this;
  }

  return SqlDom;

})();

SqlDom('select * from .container');
