// Generated by CoffeeScript 1.9.3
var SqlDom;

SqlDom = (function() {
  function SqlDom() {}

  SqlDom.prototype.foo = function() {
    return 1;
  };

  SqlDom.prototype.Update = function(query) {};

  return SqlDom;

})();
