// Generated by CoffeeScript 1.9.3
(function() {
  describe('SQL parsing', function() {
    it('Exception if query incorrect', function() {
      return expect((function() {
        return new Parser('into');
      })).toThrow();
    });
    return it('Select parsing', function() {
      var parser;
      parser = new Parser('select * from table');
      return expect(parser instanceof ParserSelect).toBe(true);
    });
  });

}).call(this);
