// Generated by CoffeeScript 1.9.3
(function() {
  describe("A suite", function() {
    return it("contains spec with an expectation", function() {
      var app;
      app = new SqlDom();
      return expect(app.foo()).toBe(1);
    });
  });

}).call(this);
