// Generated by CoffeeScript 1.9.3
(function() {
  describe("A suite", function() {
    return it("contains spec with an expectation", function() {
      SqlDom('select * from .container');
      return expect(1).toBe(1);
    });
  });

}).call(this);
